### PR TITLE
Huffman_Coding.py

### PR DESCRIPTION
**Pull request by ASHMITA-DE**
Implementation of Huffman Coding using Greedy Approach.

Huffman Coding is a technique of compressing data to reduce its size without loss of data. It is generally useful to compress the data in which there are frequently occurring characters.
It follows a Greedy approach since it deals with generating minimum length prefix-free binary codes.
It uses variable-length encoding scheme for assigning binary codes to characters depending on how frequently they occur in the given text.
Priority Queue is used for building the Huffman tree such that the character that occurs most frequently is assigned the smallest code and the one that occurs least frequently gets the largest code.
It follows this procedure: -
Create a leaf node for each character and build a min heap using all the nodes (The frequency value is used to compare two nodes in min heap)
Repeat Steps 3 to 5 while heap has more than one node
Extract two nodes, say x and y, with minimum frequency from the heap
Create a new internal node z with x as its left child and y as its right child. Also frequency(z)= frequency(x)+frequency(y)
Add z to min heap
Last node in the heap is the root of Huffman tree

### CODE REVIEW

**Comment by ASHMITA-DE** [comment]
@SpooderManEXE , as per the new rules of Hacktoberfest 2020, could you please label this pull request as "hacktoberfest-accepted", if merged? Thank you.

**Comment by SpooderManEXE** [comment]
the label is not required if it is merged however I can do that for you

**Comment by ASHMITA-DE** [comment]
Hello,
As per the new rules of Hacktoberfest 2020, could you please label this
pull request as "hacktoberfest-accepted"?
Thank you

**Comment by ASHMITA-DE** [comment]
> the label is not required if it is merged however I can do that for you

Yes please, it would be really nice of you to do so. Thank you so much.

**Comment by SpooderManEXE** [comment]
PRs count if:
Submitted during the month of October AND (
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  Submitted in a repo with the hacktoberfest topic AND (
    The PR is merged OR
    The PR has been approved
  )
)

**Comment by ASHMITA-DE** [comment]
> PRs count if:
> Submitted during the month of October AND (
> The PR is labelled as hacktoberfest-accepted by a maintainer OR
> Submitted in a repo with the hacktoberfest topic AND (
> The PR is merged OR
> The PR has been approved
> )
> )

Okay, thanks a ton ! : )

**Comment by SpooderManEXE** [comment]
np 😊

**Pull request merged**
